# Generated by Django 6.1 on 2026-08-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billgates_bhavan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billgatesbhavan',
            name='section',
            field=models.CharField(default=2026, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billgatesbhavan',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
